//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Госпитализация
    {
        public int НомерЗаписи { get; set; }
        public int НомерПациента { get; set; }
        public Nullable<int> НомерВрача { get; set; }
        public int НомерОтделения { get; set; }
        public System.DateTime ДатаПоступления { get; set; }
        public System.DateTime ДатаВыписки { get; set; }
        public int Статус { get; set; }
    
        public virtual Врач Врач { get; set; }
        public virtual Пациент Пациент { get; set; }
        public virtual Отделение Отделение { get; set; }
        public virtual Статус Статус1 { get; set; }
    }
}
