//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Диагноз
    {
        public int НомерДиагноза { get; set; }
        public int НомерПациента { get; set; }
        public string КодМКБ { get; set; }
        public string Описание { get; set; }
        public System.DateTime ДатаПостановки { get; set; }
    
        public virtual Пациент Пациент { get; set; }
    }
}
