//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Документ()
        {
            this.Пациент = new HashSet<Пациент>();
            this.ПредставительПациента = new HashSet<ПредставительПациента>();
        }
    
        public int НомерЗаписи { get; set; }
        public string НаименованиеДокумента { get; set; }
        public string Серия { get; set; }
        public string Номер { get; set; }
        public string КемВыдан { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пациент> Пациент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПредставительПациента> ПредставительПациента { get; set; }
    }
}
