//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инвалидность
    {
        public int НомерЗаписи { get; set; }
        public Nullable<int> НомерПациента { get; set; }
        public string Группа { get; set; }
        public string Описание { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Пациент Пациент { get; set; }
    }
}
