//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class КартаПациента
    {
        public int НомерЗаписи { get; set; }
        public int НомерПациента { get; set; }
        public string ГруппаКрови { get; set; }
        public string RhФактор { get; set; }
        public string КодКатегорииЛьготы { get; set; }
        public string ГруппаЗдоровья { get; set; }
        public string Курение { get; set; }
        public string НаркоманияМедикаментознаяЗависимость { get; set; }
        public string НепереносимостьПрепаратов { get; set; }
    
        public virtual Пациент Пациент { get; set; }
    }
}
