//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пациент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пациент()
        {
            this.Госпитализация = new HashSet<Госпитализация>();
            this.Диагноз = new HashSet<Диагноз>();
            this.Инвалидность = new HashSet<Инвалидность>();
            this.КартаПациента = new HashSet<КартаПациента>();
            this.ПациентАллергическаяРеакция = new HashSet<ПациентАллергическаяРеакция>();
            this.ПредставительПациента = new HashSet<ПредставительПациента>();
        }
    
        public int НомерПациента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public Nullable<int> НомерДокумента { get; set; }
        public string Пол { get; set; }
        public string СНИЛС { get; set; }
        public string ИНН { get; set; }
        public Nullable<int> Адрес { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> НомерСтраховки { get; set; }
        public string СемейноеПоложение { get; set; }
        public string Образование { get; set; }
        public string Занятость { get; set; }
        public Nullable<int> Работа { get; set; }
    
        public virtual Адрес Адрес1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Госпитализация> Госпитализация { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Диагноз> Диагноз { get; set; }
        public virtual Документ Документ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Инвалидность> Инвалидность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КартаПациента> КартаПациента { get; set; }
        public virtual Страховка Страховка { get; set; }
        public virtual Работа Работа1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПациентАллергическаяРеакция> ПациентАллергическаяРеакция { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПредставительПациента> ПредставительПациента { get; set; }
    }
}
