//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int НомерЗаписи { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Роль { get; set; }
        public Nullable<int> НомерВрача { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
    
        public virtual Врач Врач { get; set; }
        public virtual Роль Роль1 { get; set; }
    }
}
