//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class БольницаEntities : DbContext
    {
        public БольницаEntities()
            : base("name=БольницаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Адрес> Адрес { get; set; }
        public virtual DbSet<АллергическаяРеакция> АллергическаяРеакция { get; set; }
        public virtual DbSet<Врач> Врач { get; set; }
        public virtual DbSet<ВрачОтделение> ВрачОтделение { get; set; }
        public virtual DbSet<Госпитализация> Госпитализация { get; set; }
        public virtual DbSet<Диагноз> Диагноз { get; set; }
        public virtual DbSet<Документ> Документ { get; set; }
        public virtual DbSet<Инвалидность> Инвалидность { get; set; }
        public virtual DbSet<КартаПациента> КартаПациента { get; set; }
        public virtual DbSet<Отделение> Отделение { get; set; }
        public virtual DbSet<Пациент> Пациент { get; set; }
        public virtual DbSet<ПациентАллергическаяРеакция> ПациентАллергическаяРеакция { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<ПредставительПациента> ПредставительПациента { get; set; }
        public virtual DbSet<Работа> Работа { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Страховка> Страховка { get; set; }
    }
}
