//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class АллергическаяРеакция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public АллергическаяРеакция()
        {
            this.ПациентАллергическаяРеакция = new HashSet<ПациентАллергическаяРеакция>();
        }
    
        public int НомерЗаписи { get; set; }
        public string Нименование { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПациентАллергическаяРеакция> ПациентАллергическаяРеакция { get; set; }
    }
}
