//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отделение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отделение()
        {
            this.ВрачОтделение = new HashSet<ВрачОтделение>();
            this.Госпитализация = new HashSet<Госпитализация>();
        }
    
        public int НомерОтделения { get; set; }
        public string НазваниеОтделения { get; set; }
        public Nullable<int> Этаж { get; set; }
        public string Крыло { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВрачОтделение> ВрачОтделение { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Госпитализация> Госпитализация { get; set; }
    }
}
