//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПредставительПациента
    {
        public int НомерПредставителя { get; set; }
        public string НаименованиеПредставителя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчетсво { get; set; }
        public Nullable<int> НомерДокумента { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> НомерПациента { get; set; }
    
        public virtual Документ Документ { get; set; }
        public virtual Пациент Пациент { get; set; }
    }
}
